<?php

namespace Database\Seeders\pkg_Blogs;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogPostsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('blog_posts')->insert([
            [
                'title' => 'The Future of Artificial Intelligence',
                'slug' => 'future-of-ai',
                'content' => 'Artificial Intelligence is transforming the world...',
                'excerpt' => 'A deep dive into the future of AI and its applications.',
                'meta_title' => 'AI Future - Insights & Trends',
                'meta_description' => 'Explore the latest advancements in AI.',
                'blog_author_id' => 1,
                'blog_category_id' => 1,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_1.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '10 Tips for Healthy Living',
                'slug' => '10-tips-healthy-living',
                'content' => 'Living a healthy life requires balance and good habits...',
                'excerpt' => 'Discover the best practices for maintaining a healthy lifestyle.',
                'meta_title' => 'Healthy Living Tips',
                'meta_description' => 'A guide to achieving optimal health.',
                'blog_author_id' => 2,
                'blog_category_id' => 2,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_2.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Investment Strategies for Beginners',
                'slug' => 'investment-strategies-beginners',
                'content' => 'Starting to invest can be overwhelming, but with the right approach...',
                'excerpt' => 'Learn how to start investing with these simple strategies.',
                'meta_title' => 'Beginner Investment Strategies',
                'meta_description' => 'Financial tips to grow your wealth.',
                'blog_author_id' => 3,
                'blog_category_id' => 3,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_3.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'How to Start a Successful Business',
                'slug' => 'how-to-start-business',
                'content' => 'Starting a business requires planning, market research...',
                'excerpt' => 'Key steps to launching your own business.',
                'meta_title' => 'Startup Business Guide',
                'meta_description' => 'Insights on building a successful startup.',
                'blog_author_id' => 4,
                'blog_category_id' => 4,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_4.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Top 5 Travel Destinations for 2025',
                'slug' => 'top-5-travel-destinations-2025',
                'content' => 'Looking for your next travel adventure? Check out these top places...',
                'excerpt' => 'Best travel spots for your next vacation.',
                'meta_title' => 'Top Travel Destinations',
                'meta_description' => 'Explore beautiful places around the world.',
                'blog_author_id' => 5,
                'blog_category_id' => 5,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_5.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Ultimate Guide to Cooking Delicious Meals',
                'slug' => 'ultimate-guide-cooking',
                'content' => 'Cooking is an art, and with the right techniques...',
                'excerpt' => 'Improve your cooking skills with expert tips.',
                'meta_title' => 'Cooking Guide',
                'meta_description' => 'Learn how to make delicious meals at home.',
                'blog_author_id' => 6,
                'blog_category_id' => 6,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_6.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Evolution of Sports and Fitness',
                'slug' => 'evolution-sports-fitness',
                'content' => 'From traditional workouts to modern fitness trends...',
                'excerpt' => 'How sports and fitness have changed over the years.',
                'meta_title' => 'Sports Evolution',
                'meta_description' => 'A history of sports and modern fitness.',
                'blog_author_id' => 7,
                'blog_category_id' => 7,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_7.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why Education is the Key to Success',
                'slug' => 'why-education-key-success',
                'content' => 'Education shapes the future by providing knowledge...',
                'excerpt' => 'The importance of education in personal and professional growth.',
                'meta_title' => 'Education & Success',
                'meta_description' => 'How education plays a role in success.',
                'blog_author_id' => 8,
                'blog_category_id' => 8,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_8.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Top 10 Must-Watch Movies of the Year',
                'slug' => 'top-10-movies',
                'content' => 'From action-packed blockbusters to thought-provoking dramas...',
                'excerpt' => 'A list of must-watch movies this year.',
                'meta_title' => 'Best Movies of the Year',
                'meta_description' => 'A guide to the top movies you should watch.',
                'blog_author_id' => 9,
                'blog_category_id' => 9,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_9.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Future of Space Exploration',
                'slug' => 'future-space-exploration',
                'content' => 'Space travel is evolving rapidly with new technologies...',
                'excerpt' => 'What the future holds for space exploration.',
                'meta_title' => 'Space Exploration',
                'meta_description' => 'Discover the next steps in space travel.',
                'blog_author_id' => 10,
                'blog_category_id' => 10,
                'featured_image' => 'http://127.0.0.1:8000/storage/seed_images/blog_feature_images/blog_10.jpg',
                'is_published' => true,
                'published_at' => now(),
                'views_count' => rand(100, 5000),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

}
